require:
  - rubocop-performance

AllCops:
  EnabledByDefault: true
  Exclude:
    - calculated.gemspec

  TargetRubyVersion: 2.7.1

Bundler/GemComment:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument
  IndentationWidth: 4

Layout/FirstArgumentIndentation:
  IndentationWidth: 4

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/FirstMethodParameterLineBreak:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Max: 80

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: always_braces

Style/Copyright:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/InlineComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - gem
    - puts
    - raise
    - require
    - require_relative
    - source

Style/MissingElse:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OptionHash:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true
